#Question:
#    Python has many built-in functions, and if you do not know how to use it, you can read document online or find some books. But Python has a built-in document function for every built-in functions.
#    Please write a program to print some Python built-in functions documents, such as abs(), int(), raw_input()
#    And add document for your own function


print(abs.__doc__)
print(list.__doc__)
print(len.__doc__)
print(round.__doc__)
print(int.__doc__)
print(float.__doc__)
print(id.__doc__)
print(type.__doc__)
print(str.__doc__)
print(tuple.__doc__)
print(dict.__doc__)
print(input.__doc__)
print(print.__doc__)
print(True.__doc__)
print(False.__doc__)
print(bool.__doc__)
print(set.__doc__)
print(bin.__doc__)
print(oct.__doc__)
print(hex.__doc__)
print(min.__doc__)
print(max.__doc__)
print(sum.__doc__)
print(chr.__doc__)
print(ascii.__doc__)
print(map.__doc__)
print(filter.__doc__)
print(range.__doc__)
print(slice.__doc__)
